# Generated by Django 4.1.2 on 2022-11-03 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('Mode_of_delivery', models.CharField(choices=[('BYHAND', 'BYHAND'), ('COURIOR', 'COURIOR'), ('OTHER', 'OTHER')], max_length=50)),
                ('label_code', models.CharField(default='', max_length=20)),
                ('issued_to', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.category')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.description')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(max_length=255)),
                ('is_consumable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Subcategory',
            },
        ),
        migrations.CreateModel(
            name='Supp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Supp',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='imdapp.supp')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('type', models.CharField(choices=[('CONSUMABLE', 'CONSUMABLE'), ('NON-COMSUMABLE', 'NON-COMSUMABLE')], max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('Mode_of_delivery', models.CharField(choices=[('BYHAND', 'BYHAND'), ('COURIOR', 'COURIOR'), ('OTHER', 'OTHER')], max_length=50)),
                ('label_code', models.CharField(default='', max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'GOOD'), ('TORED', 'TORED'), ('DAMAGED', 'DAMAGED')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.category')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.description')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.supp')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=1)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salebillno', to='imdapp.salebill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitem', to='imdapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetailsbillno', to='imdapp.salebill')),
            ],
        ),
        migrations.AddField(
            model_name='salebill',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdapp.subcategory'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('perprice', models.IntegerField(default=1)),
                ('totalprice', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasebillno', to='imdapp.purchasebill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='imdapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedetailsbillno', to='imdapp.purchasebill')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='imdapp.supplier'),
        ),
    ]
