# Generated by Django 4.1.2 on 2022-11-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('Mtr', 'Mtr'), ('Cm', 'Cm'), ('mm', 'mm'), ('Kg', 'Kg'), ('gm', 'gm'), ('Ltr', 'Ltr'), ('SqMtr', 'SqMtr'), ('SqCm', 'SqCm'), ('CuM', 'CuM'), ('Ream', 'Ream'), ('Doz', 'Doz'), ('Pkts', 'Pkts'), ('Pairs', 'Pairs'), ('Rolls', 'Rolls')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
